### PR TITLE
Add Lyft party

### PR DESCRIPTION
**Pull request by sberrevoets**
This adds the Lyft party to the list. I wasn't sure how the icon and logo URLs were generated, so I left those empty but the images are part of the PR. Please let me know how I can get the link for the images and I'll be sure to add them!

### CODE REVIEW

**Comment by genadyo** [comment]
Wow, Impressing!

**Comment by sberrevoets** [comment]
Thanks! Although now it doesn't show images, because there is no URL - any chance you could add those?

**Comment by genadyo** [comment]
Took me 3 tries but I fixed it now.

**Comment by genadyo** [comment]
And now I event compressed that huge JPG!

**Pull request merged**
